Error w/ `rpmbuild`: python3-devel is needed
[nebula-toolbox@44544e1114fd hellocopr]$ tito build --rpm --test
Creating output directory: /tmp/tito
WARNING: unable to lookup latest package tag, building untagged test project
WARNING: .tito/packages/hellocopr doesn't exist in git, using current directory
Building package [hellocopr-0.0.0-0]
Wrote: /tmp/tito/hellocopr-git-1.64cbdb3.tar.gz

warning: source_date_epoch_from_changelog set but %changelog is missing
error: Failed build dependencies:
	python3-devel is needed by hellocopr-0.0.0-0.git.1.64cbdb3.fc40.noarch

RPM build warnings:
    source_date_epoch_from_changelog set but %changelog is missing

ERROR: Error running command: rpmbuild   --eval '%undefine scl' --define "_topdir /tmp/tito/rpmbuild-hellocoprtf0qt7sk" --define "_sourcedir /tmp/tito/rpmbuild-hellocoprtf0qt7sk/SOURCES" --define "_builddir /tmp/tito/rpmbuild-hellocoprtf0qt7sk/BUILD" --define "_srcrpmdir /tmp/tito" --define "_rpmdir /tmp/tito"   --clean  -ba /tmp/tito/rpmbuild-hellocoprtf0qt7sk/SOURCES/hellocopr-git-1.64cbdb3/hellocopr.spec

Status code: 11

Command output: ['', 'warning: source_date_epoch_from_changelog set but %changelog is missing', 'error: Failed build dependencies:', '\tpython3-devel is needed by hellocopr-0.0.0-0.git.1.64cbdb3.fc40.noarch', '', 'RPM build warnings:', '    source_date_epoch_from_changelog set but %changelog is missing']

ERROR: Please run 'dnf builddep hellocopr.spec' as root.
[nebula-toolbox@44544e1114fd hellocopr]$ tree
.
├── LICENSE
├── README.md
└── hellocopr.spec

1 directory, 3 files